/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVoting } from "./IVoting";
export type { Voting } from "./Voting";
export * as factories from "./factories";
export { IVoting__factory } from "./factories/IVoting__factory";
export { Voting__factory } from "./factories/Voting__factory";
