/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface VotingInterface extends utils.Interface {
  functions: {
    "Comission()": FunctionFragment;
    "addCandidate(uint256,address)": FunctionFragment;
    "addVoting(address[],uint256)": FunctionFragment;
    "checkCandidate(uint256,address)": FunctionFragment;
    "counter()": FunctionFragment;
    "deleteCandidate(address,uint256)": FunctionFragment;
    "editVotingPeriod(uint256,uint256)": FunctionFragment;
    "getVotingInfo(uint256)": FunctionFragment;
    "maxCandidates()": FunctionFragment;
    "minCandidates()": FunctionFragment;
    "owner()": FunctionFragment;
    "setMaxCandidates(uint256)": FunctionFragment;
    "startVoting(uint256)": FunctionFragment;
    "takePartInVoting(uint256,address)": FunctionFragment;
    "withDrawPrize(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "Comission"
      | "addCandidate"
      | "addVoting"
      | "checkCandidate"
      | "counter"
      | "deleteCandidate"
      | "editVotingPeriod"
      | "getVotingInfo"
      | "maxCandidates"
      | "minCandidates"
      | "owner"
      | "setMaxCandidates"
      | "startVoting"
      | "takePartInVoting"
      | "withDrawPrize"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "Comission", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addCandidate",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addVoting",
    values: [PromiseOrValue<string>[], PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "checkCandidate",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "counter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deleteCandidate",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "editVotingPeriod",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotingInfo",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "maxCandidates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minCandidates",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setMaxCandidates",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "startVoting",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "takePartInVoting",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "withDrawPrize",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "Comission", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addCandidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addVoting", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkCandidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "counter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deleteCandidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "editVotingPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVotingInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxCandidates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minCandidates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMaxCandidates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startVoting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "takePartInVoting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withDrawPrize",
    data: BytesLike
  ): Result;

  events: {
    "candidateInfo(uint256,address,bool)": EventFragment;
    "votingDraftCreated(uint256)": EventFragment;
    "votingStarted(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "candidateInfo"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "votingDraftCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "votingStarted"): EventFragment;
}

export interface candidateInfoEventObject {
  id: BigNumber;
  candidate: string;
  existOnThisVoting: boolean;
}
export type candidateInfoEvent = TypedEvent<
  [BigNumber, string, boolean],
  candidateInfoEventObject
>;

export type candidateInfoEventFilter = TypedEventFilter<candidateInfoEvent>;

export interface votingDraftCreatedEventObject {
  id: BigNumber;
}
export type votingDraftCreatedEvent = TypedEvent<
  [BigNumber],
  votingDraftCreatedEventObject
>;

export type votingDraftCreatedEventFilter =
  TypedEventFilter<votingDraftCreatedEvent>;

export interface votingStartedEventObject {
  id: BigNumber;
  startDate: BigNumber;
}
export type votingStartedEvent = TypedEvent<
  [BigNumber, BigNumber],
  votingStartedEventObject
>;

export type votingStartedEventFilter = TypedEventFilter<votingStartedEvent>;

export interface Voting extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VotingInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    Comission(overrides?: CallOverrides): Promise<[number]>;

    addCandidate(
      _id: PromiseOrValue<BigNumberish>,
      _candidate: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addVoting(
      _candidates: PromiseOrValue<string>[],
      _period: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    checkCandidate(
      _id: PromiseOrValue<BigNumberish>,
      _candidate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    counter(overrides?: CallOverrides): Promise<[BigNumber]>;

    deleteCandidate(
      _candidate: PromiseOrValue<string>,
      _id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    editVotingPeriod(
      _id: PromiseOrValue<BigNumberish>,
      _newPeriod: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getVotingInfo(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, BigNumber, BigNumber, BigNumber, BigNumber, string]>;

    maxCandidates(overrides?: CallOverrides): Promise<[BigNumber]>;

    minCandidates(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    setMaxCandidates(
      _maxCandidates: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    startVoting(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    takePartInVoting(
      _id: PromiseOrValue<BigNumberish>,
      _candidate: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withDrawPrize(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  Comission(overrides?: CallOverrides): Promise<number>;

  addCandidate(
    _id: PromiseOrValue<BigNumberish>,
    _candidate: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addVoting(
    _candidates: PromiseOrValue<string>[],
    _period: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  checkCandidate(
    _id: PromiseOrValue<BigNumberish>,
    _candidate: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  counter(overrides?: CallOverrides): Promise<BigNumber>;

  deleteCandidate(
    _candidate: PromiseOrValue<string>,
    _id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  editVotingPeriod(
    _id: PromiseOrValue<BigNumberish>,
    _newPeriod: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getVotingInfo(
    _id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[boolean, BigNumber, BigNumber, BigNumber, BigNumber, string]>;

  maxCandidates(overrides?: CallOverrides): Promise<BigNumber>;

  minCandidates(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  setMaxCandidates(
    _maxCandidates: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  startVoting(
    _id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  takePartInVoting(
    _id: PromiseOrValue<BigNumberish>,
    _candidate: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withDrawPrize(
    _id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    Comission(overrides?: CallOverrides): Promise<number>;

    addCandidate(
      _id: PromiseOrValue<BigNumberish>,
      _candidate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addVoting(
      _candidates: PromiseOrValue<string>[],
      _period: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    checkCandidate(
      _id: PromiseOrValue<BigNumberish>,
      _candidate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    counter(overrides?: CallOverrides): Promise<BigNumber>;

    deleteCandidate(
      _candidate: PromiseOrValue<string>,
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    editVotingPeriod(
      _id: PromiseOrValue<BigNumberish>,
      _newPeriod: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getVotingInfo(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, BigNumber, BigNumber, BigNumber, BigNumber, string]>;

    maxCandidates(overrides?: CallOverrides): Promise<BigNumber>;

    minCandidates(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    setMaxCandidates(
      _maxCandidates: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    startVoting(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    takePartInVoting(
      _id: PromiseOrValue<BigNumberish>,
      _candidate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    withDrawPrize(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "candidateInfo(uint256,address,bool)"(
      id?: PromiseOrValue<BigNumberish> | null,
      candidate?: PromiseOrValue<string> | null,
      existOnThisVoting?: null
    ): candidateInfoEventFilter;
    candidateInfo(
      id?: PromiseOrValue<BigNumberish> | null,
      candidate?: PromiseOrValue<string> | null,
      existOnThisVoting?: null
    ): candidateInfoEventFilter;

    "votingDraftCreated(uint256)"(
      id?: PromiseOrValue<BigNumberish> | null
    ): votingDraftCreatedEventFilter;
    votingDraftCreated(
      id?: PromiseOrValue<BigNumberish> | null
    ): votingDraftCreatedEventFilter;

    "votingStarted(uint256,uint256)"(
      id?: PromiseOrValue<BigNumberish> | null,
      startDate?: null
    ): votingStartedEventFilter;
    votingStarted(
      id?: PromiseOrValue<BigNumberish> | null,
      startDate?: null
    ): votingStartedEventFilter;
  };

  estimateGas: {
    Comission(overrides?: CallOverrides): Promise<BigNumber>;

    addCandidate(
      _id: PromiseOrValue<BigNumberish>,
      _candidate: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addVoting(
      _candidates: PromiseOrValue<string>[],
      _period: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    checkCandidate(
      _id: PromiseOrValue<BigNumberish>,
      _candidate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    counter(overrides?: CallOverrides): Promise<BigNumber>;

    deleteCandidate(
      _candidate: PromiseOrValue<string>,
      _id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    editVotingPeriod(
      _id: PromiseOrValue<BigNumberish>,
      _newPeriod: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getVotingInfo(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxCandidates(overrides?: CallOverrides): Promise<BigNumber>;

    minCandidates(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    setMaxCandidates(
      _maxCandidates: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    startVoting(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    takePartInVoting(
      _id: PromiseOrValue<BigNumberish>,
      _candidate: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withDrawPrize(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    Comission(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addCandidate(
      _id: PromiseOrValue<BigNumberish>,
      _candidate: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addVoting(
      _candidates: PromiseOrValue<string>[],
      _period: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    checkCandidate(
      _id: PromiseOrValue<BigNumberish>,
      _candidate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    counter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deleteCandidate(
      _candidate: PromiseOrValue<string>,
      _id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    editVotingPeriod(
      _id: PromiseOrValue<BigNumberish>,
      _newPeriod: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getVotingInfo(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxCandidates(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minCandidates(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setMaxCandidates(
      _maxCandidates: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    startVoting(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    takePartInVoting(
      _id: PromiseOrValue<BigNumberish>,
      _candidate: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withDrawPrize(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
